### ISSUE TITLE
Unable to save CSS

### ISSUE THREAD

**Issue by Fannon** [erinata/SublimeMarkdownBuild#3]
Hi there!

I can't build markdown text to html. This is what happens:

```
Writing file /C/Users/Fannon/AppData/Local/Temp/fz3temp-1/custom.css with encoding UTF-8
error: Unable to save C:\Users\Fannon\AppData\Local\Temp\fz3temp-1\custom.css
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
  File ".\exec.py", line 109, in run
  File ".\ntpath.py", line 205, in dirname
  File ".\ntpath.py", line 170, in split
  File ".\ntpath.py", line 125, in splitdrive
TypeError: 'NoneType' object is unsubscriptable
```

Even running Sublime as Admin doesn't work.

Greets,
Simon

**Comment by erinata** [comment]
This is strange...... MarkdownBuild use a file named markdown.css (instead of custom.css) and it doesn't save any css file. It embed the css file into the html.

Can you try uninstalling MarkdownBuild and reinstall it?
